import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import WeatherIcon from '../public/weathericon'
import cities from 'cities.json'

const Home: NextPage = () => {

  interface City {
    country: string,
    lat: string,
    lng: string,
    name: string
  }

  const allCities:Array<City> = Object.values(cities)

  const brazilcities:Array<City> = []

  allCities.map(i => {
    if (i.country == 'BR') {
      brazilcities.push(i)
    }
  })
  brazilcities.sort(function(a,b){
    return a.name.localeCompare(b.name);
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.section}>
          <div>
            <h1>
              Cidades
            </h1>
          </div>
          <div className={styles.cities}>
          {
              brazilcities.map(i => {
                return <div className={`${styles.city} ${styles.show}`}><h4>{i.name}</h4></div>
              })
            }
          </div>
        </div>
        <div className={styles.section}>
          <h1>Clima</h1>
          <h3>Qual será o clima de hoje?...</h3>
          <WeatherIcon />
        </div>
      </main>
    </div>
  )
}

export default Home
